package dems;

/**
* dems/EventManagementServiceImplHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EventManagementService.idl
* Sunday, February 23, 2020 8:25:50 o'clock PM EST
*/

public final class EventManagementServiceImplHolder implements org.omg.CORBA.portable.Streamable
{
  public dems.EventManagementServiceImpl value = null;

  public EventManagementServiceImplHolder ()
  {
  }

  public EventManagementServiceImplHolder (dems.EventManagementServiceImpl initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = EventManagementServiceImplHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    EventManagementServiceImplHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return EventManagementServiceImplHelper.type ();
  }

}
